### ISSUE TITLE
Hello World example does not work with Rust  1.92.0

### ISSUE THREAD

**Issue by goto-dev-null** [foldright/tiny_http#3]
I am still very very new to Rust but I cannot get the most straightforward example to compile at all.

rustc 1.92.0 (ded5c06cf 2025-12-08) (Chimera Linux)

```
error[E0277]: the trait bound `fn() -> ... {hello_world}: RequestHandler` is not satisfied
   --> src/main.rs:23:25
    |
 23 |         .route("/", get(hello_world))
    |                     --- ^^^^^^^^^^^ unsatisfied trait bound
    |                     |
    |                     required by a bound introduced by this call
    |
    = help: the trait `micro_web::handler::RequestHandler` is not implemented for fn item `fn() -> impl Future<Output = &'static str> {hello_world}`
    = help: the following other types implement trait `micro_web::handler::RequestHandler`:
              &dyn micro_web::handler::RequestHandler
              Box<(dyn micro_web::handler::RequestHandler + 'static)>
              Box<T>
              EncodeRequestHandler<H>
              FnHandler<F, Args>
              date::date_service_decorator::DateResponseHandler<H>
note: required by a bound in `micro_web::router::get`
   --> /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/micro-web-0.1.1/src/router/mod.rs:149:1
    |
149 | method_router_filter!(get, get_method);
    | ^^^^^^^^^^^^^^^^^^^^^^---^^^^^^^^^^^^^
    | |                     |
    | |                     required by a bound in this function
    | required by this bound in `get`
    = note: the full name for the type has been written to '/home/user/me/dev/meep/target/debug/deps/meep-08cdb3e6325c331f.long-type-2027444226930024819.txt'
    = note: consider using `--verbose` to print the full type name to the console
    = note: this error originates in the macro `method_router_filter` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `fn() -> ... {default_handler}: RequestHandler` is not satisfied
  --> src/main.rs:35:26
   |
35 |         .default_handler(default_handler)
   |          --------------- ^^^^^^^^^^^^^^^ unsatisfied trait bound
   |          |
   |          required by a bound introduced by this call
   |
   = help: the trait `micro_web::handler::RequestHandler` is not implemented for fn item `fn() -> impl Future<Output = &'static str> {default_handler}`
   = help: the following other types implement trait `micro_web::handler::RequestHandler`:
             &dyn micro_web::handler::RequestHandler
             Box<(dyn micro_web::handler::RequestHandler + 'static)>
             Box<T>
             EncodeRequestHandler<H>
             FnHandler<F, Args>
             date::date_service_decorator::DateResponseHandler<H>
note: required by a bound in `micro_web::server::ServerBuilder::default_handler`
  --> /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/micro-web-0.1.1/src/server.rs:77:60
   |
77 |     pub fn default_handler(mut self, request_handler: impl RequestHandler + 'static) -> Self {
   |                                                            ^^^^^^^^^^^^^^ required by this bound in `ServerBuilder::default_handler`
   = note: the full name for the type has been written to '/home/user/me/dev/meep/target/debug/deps/meep-08cdb3e6325c331f.long-type-1445402062995762735.txt'
   = note: consider using `--verbose` to print the full type name to the console

For more information about this error, try `rustc --explain E0277`.
```

**Comment by zavakid** [comment]
> /home/user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/micro-web-0.1.1/src/server.rs:77:60
@goto-dev-null Thinks for your feedback, I see you're using 0.1.1 here, you can use 0.3.0 ( https://crates.io/crates/micro-web )

**Comment by goto-dev-null** [comment]
Oh, my bad...I don't know why it was set to use 0.1. I thought I had just done `cargo add micro-web`.

Thanks for the super fast response!
